version: "3.8"

services:
  website:
     restart: always
     build:
       context: .
       dockerfile: Dockerfile
     ports:
       - "5000:5000"
     env_file:
       - .env
       - .env.example
