version: "3.8"

services:
  website:
     restart: always
     build:
       context: .
       dockerfile: Dockerfile
     ports:
       - "5000:5000"
     environment:
       - HOST="127.0.0.1"
       - PORT=5000
