version: "3.8"

services:
  website:
     restart: always
     build:
       context: .
       dockerfile: Dockerfile
     ports:
       - "42069:42069"
     environment:
       - HOST=127.0.0.1
       - PORT=42069
